Components/NavigationMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MarinaCargo.Models;

namespace MarinaCargo.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepo _repo;

        public NavigationMenuViewComponent(IProductRepo repo)
        {
            _repo = repo;
        }

        public IViewComponentResult Invoke()
        {
            return View(_repo.Products.Select(x => x.Category).Distinct().OrderBy(x => x));
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MarinaCargo.Models;
using MarinaCargo.Models.ViewModels;

namespace MarinaCargo.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepo repository;
        public int PageSize = 4;
        public ProductController(IProductRepo repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
         => View(new ProductsListViewModel
            {
             Products = repository.Products
             .Where(p => category == null || p.Category == category)
             .OrderBy(p => p.ProductID)
             .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = category == null ? repository.Products.Count() : repository.Products.Where(e => e.Category == category).Count()
                    },
                    CurrentCategory = category
        });

    }
}

Views/Product/List.cshtml
@using MarinaCargo.Models.ViewModels
@model ProductsListViewModel

@if (Model.CurrentCategory != null)
{
    ViewBag.Title = Model.CurrentCategory;
}
else { ViewBag.Title = "All Products"; }

<div class="col col-md-3">
    @await Component.InvokeAsync("NavigationMenu")
</div>
<div class="col col-md-9">
    @if (Model.CurrentCategory != null)
    {
        <h1><strong>@Model.CurrentCategory</strong></h1>
    }
    else {<h1><strong>All Products</strong></h1>}
    <hr />
    @foreach (var p in Model.Products)
    {
        @Html.Partial("ProductSummary", p)
    }
    <div page-model="@Model.PagingInfo" page-action="List" page-classes-enabled="true"
         page-class="btn" page-class-normal="btn-default"
         page-class-selected="btn-primary" page-url-category="@Model.CurrentCategory" btn-group float-right">
    </div>
    <br />
</div>